export const voiceProfiles=Object.freeze({PLAYER:{pitch:126,formant:650},EDDIE:{pitch:172,formant:980},LEON:{pitch:138,formant:720},NICO:{pitch:103,formant:540},MARA:{pitch:205,formant:1150},REFEREE:{pitch:117,formant:600},OPPONENT:{pitch:145,formant:820}});
export function createBasementAudio(){
 let context=null,master=null,hum=null,muted=false,epoch=0,spoken=null;
 const live=new Set(),limits=new Map();
 function unlock(basement=true){const Audio=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Audio)return;try{if(!context){context=new Audio();master=context.createGain();master.gain.value=muted?0:.6;const limiter=context.createDynamicsCompressor();limiter.threshold.value=-12;limiter.ratio.value=8;master.connect(limiter);limiter.connect(context.destination);}context.resume().catch(()=>{});if(basement&&!hum){hum=context.createOscillator();hum.type='sine';hum.frequency.value=58;const g=context.createGain();g.gain.value=.016;hum.connect(g);g.connect(master);hum.start();}}catch{}}
 function allowed(key,gap){if(!context||muted||context.state==='suspended')return false;const now=context.currentTime;if(now-(limits.get(key)??-Infinity)<gap)return false;limits.set(key,now);return true;}
 function track(source,end,nodes,start=context.currentTime){live.add(source);source.onended=()=>{live.delete(source);for(const node of [source,...nodes])node.disconnect();};source.start(start);source.stop(end);}
 function tone(frequency,endFrequency,duration,volume,type='sine',pan=0){if(!context)return;const t=context.currentTime,o=context.createOscillator(),g=context.createGain(),p=context.createStereoPanner();o.type=type;o.frequency.setValueAtTime(frequency,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,endFrequency),t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);p.pan.value=pan;o.connect(g);g.connect(p);p.connect(master);track(o,t+duration+.02,[g,p]);}
 function noise(duration,volume,frequency,pan=0,delay=0){if(!context)return;const t=context.currentTime+delay,b=context.createBuffer(1,Math.ceil(context.sampleRate*duration),context.sampleRate),data=b.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,1.5);const source=context.createBufferSource(),filter=context.createBiquadFilter(),g=context.createGain(),p=context.createStereoPanner();source.buffer=b;filter.type='bandpass';filter.frequency.value=frequency;filter.Q.value=.6;g.gain.value=volume;p.pan.value=pan;source.connect(filter);filter.connect(g);g.connect(p);p.connect(master);track(source,t+duration,[filter,g,p],t);}
 function grunt(character,kind='effort',strength=.5,pan=0){if(!allowed('voice:'+character+':'+kind,kind==='hurt'?.55:.4))return;const profile=voiceProfiles[character]||voiceProfiles.OPPONENT,variation=.94+Math.random()*.12,duration=kind==='hurt'?.24+strength*.17:.15,t=context.currentTime,o=context.createOscillator(),filter=context.createBiquadFilter(),g=context.createGain(),p=context.createStereoPanner();o.type='sawtooth';o.frequency.setValueAtTime(profile.pitch*variation,t);o.frequency.exponentialRampToValueAtTime(profile.pitch*(kind==='hurt'?.63:.78),t+duration);filter.type='bandpass';filter.frequency.value=profile.formant;filter.Q.value=2.2;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.045+strength*.035,t+.025);g.gain.exponentialRampToValueAtTime(.0001,t+duration);p.pan.value=pan;o.connect(filter);filter.connect(g);g.connect(p);p.connect(master);track(o,t+duration+.02,[filter,g,p]);noise(duration,.025,1800,pan);}
 function swing(character,hand,power=1,pan=0){if(!allowed('swing:'+character,.22))return;noise(.18,.07*power,hand?1150:1450,pan,.12);grunt(character,'effort',.4,pan);}
 function impact(character,speed,blocked=false,pan=0,region='head'){if(!allowed('impact',.055))return;const force=Math.min(1,Math.max(.12,speed/14));tone(blocked?195:region==='torso'?72:105,blocked?110:42,.12+force*.09,.08+force*.16,'sine',pan);noise(blocked?.09:.14,blocked?.08:.08+force*.15,blocked?1900:region==='torso'?520:1100,pan);if(!blocked)grunt(character,'hurt',force,pan);}
 function step(character,pan=0){if(!allowed('step:'+character,.23))return;noise(.075,.035,420,pan);tone(75,45,.08,.025,'sine',pan);}
 function bell(){if(!allowed('bell',.5))return;for(const f of [725,1119,1577])tone(f,f*.996,1.8,.045);}
 function knockout(character,pan=0){if(!allowed('knockout',2))return;grunt(character,'hurt',1,pan);tone(65,28,.48,.16,'sine',pan);noise(.35,.12,320,pan);for(const offset of [-.7,0,.7])noise(.9,.035,1000,offset);}
 function stopVoices(){epoch++;globalThis.speechSynthesis?.cancel();spoken=null;}
 function speak(character,line){stopVoices();const speech=globalThis.speechSynthesis,Utterance=globalThis.SpeechSynthesisUtterance;if(!speech||!Utterance||!context||muted)return;const utterance=new Utterance(line),voices=speech.getVoices().filter(v=>/^en/i.test(v.lang));const female=character==='MARA';utterance.voice=voices.find(v=>female?/zira|female|susan|jenny/i.test(v.name):/david|mark|male|george|guy/i.test(v.name))||voices[0]||null;utterance.lang='en-US';utterance.pitch=({EDDIE:.98,LEON:.78,NICO:.62,MARA:1.08,REFEREE:.72})[character]||.9;utterance.rate=({EDDIE:1.10,LEON:.96,NICO:.86,MARA:1,REFEREE:.92})[character]||1;utterance.volume=.65;spoken=utterance;speech.speak(utterance);}
 function stop(){stopVoices();if(hum){hum.stop();hum.disconnect();hum=null;}for(const source of live){try{source.stop();}catch{}}limits.clear();}
 function toggle(){muted=!muted;if(master)master.gain.value=muted?0:.6;if(muted)stopVoices();return muted;}
 return {unlock,bell,stop,toggle,swing,impact,step,knockout,speak,stopVoices,get muted(){return muted;}};
}
