export function createMultiplayer({onStart,onLeave,onPunch,onPush=()=>{}}){
 const root=document.querySelector('#party-screen'),$=s=>document.querySelector(s);
 if(!root?.addEventListener)return {get active(){return false;},get guest(){return false;},get paused(){return false;},remote:{x:0,z:0,guard:false,slip:0,at:0},snapshot:null,sendInput(){},sendState(){},punch(){},push(){},leave(){},showRematch(){}};
 let token=null,role=0,code='',stream=null,match=0,active=false,connected=false,lastInput=0,lastState=0,inputSeq=0,punchSeq=0,inputBusy=false,stateBusy=false;
 const api={remote:{x:0,z:0,guard:false,slip:0,at:0},snapshot:null,get active(){return active;},get canSendState(){return active&&role===0&&performance.now()-lastState>=40;},get guest(){return active&&role===1;},get paused(){return active&&!connected;}};
 const status=text=>$('#party-status').textContent=text;
 function live(action,data){if(stream?.readyState!==1||stream.bufferedAmount>128000)return false;stream.send(JSON.stringify({action,...data,match}));return true;}
 async function post(action,data={}){const response=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json',...(token?{'Authorization':'Bearer '+token}:{})},body:JSON.stringify({...data,match})});const body=await response.json();if(!response.ok)throw Error(body.error||'Connection failed.');return body;}
 function displayParty(data){connected=data.players.every(p=>p?.connected);$('#party-code').textContent=code;$('#party-members').textContent=data.players[1]?'2 / 2 PLAYERS':'1 / 2 PLAYERS';$('#party-ready').disabled=!connected||data.players[role]?.ready;$('#party-ready').textContent=data.players[role]?.ready?'WAITING FOR FRIEND':'READY TO FIGHT';status(!data.players[1]?'Share the code with your friend.':connected?'Both players are here. Ready up to fight.':'Waiting for the connection…');if(active&&!data.playing){active=false;onLeave();open();}}
 function connect(){stream?.close();const socket=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/api/events?token='+encodeURIComponent(token));stream=socket;stream.onmessage=e=>{const data=JSON.parse(e.data);if(data.type==='party')displayParty(data);if(data.type==='start'&&data.match!==match){match=data.match;active=true;connected=true;api.snapshot=null;root.hidden=true;onStart(role);}if(data.type==='input'){api.remote={...data.input,at:performance.now()};}if(data.type==='punch')onPunch(data.hand,data.kind);if(data.type==='push')onPush();if(data.type==='state')api.snapshot=data.state;if(data.type==='paused'){connected=false;status(data.message);}if(data.type==='closed'){leave();open();status(data.message);}};stream.onerror=()=>{connected=false;status('Reconnecting to your party…');};stream.onclose=()=>{if(stream===socket&&token){connected=false;status('Reconnecting to your party…');setTimeout(()=>{if(stream===socket&&token)connect();},1000);}};}
 function open(){root.hidden=false;$('#party-entry').hidden=!!token;$('#party-room').hidden=!token;$('#main-menu').hidden=true;}
 async function enter(action){const button=action==='create'?$('#create-party'):$('#join-party');button.disabled=true;try{const data=await post(action,{code:$('#join-code').value});token=data.token;role=data.role;code=data.code;match=0;active=false;connected=false;open();connect();}catch(error){status(error.message);}finally{button.disabled=false;}}
 function leave(){const old=token;if(old)fetch('/api/leave',{method:'POST',headers:{'Authorization':'Bearer '+old,'Content-Type':'application/json'},body:'{}',keepalive:true}).catch(()=>{});stream?.close();stream=null;token=null;active=false;connected=false;api.snapshot=null;api.remote={x:0,z:0,guard:false,slip:0,at:0};root.hidden=true;onLeave();}
 $('#multiplayer-button').onclick=()=>{open();status('Create a party or enter your friend’s code.');};$('#create-party').onclick=()=>enter('create');$('#join-form').onsubmit=e=>{e.preventDefault();enter('join');};$('#party-back').onclick=leave;$('#party-ready').onclick=async()=>{try{$('#party-ready').disabled=true;await post('ready');}catch(error){$('#party-ready').disabled=false;status(error.message);}};
 addEventListener('pagehide',()=>{if(token)fetch('/api/leave',{method:'POST',headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json'},body:'{}',keepalive:true}).catch(()=>{});});
 api.leave=leave;api.showRematch=()=>{active=false;onLeave();open();$('#party-ready').disabled=false;$('#party-ready').textContent='READY FOR REMATCH';status('Ready up together for another fight.');};
 api.punch=(hand,kind)=>{if(api.guest&&!api.paused)live('punch',{hand,kind,seq:++punchSeq});};
 api.push=()=>{if(api.guest&&!api.paused)live('push',{seq:++punchSeq});};
 api.sendInput=input=>{const now=performance.now();if(!api.guest||inputBusy||now-lastInput<40)return;lastInput=now;if(live('input',{...input,seq:++inputSeq}))return;inputBusy=true;post('input',{...input,seq:++inputSeq}).catch(()=>{if(stream?.readyState!==1)connected=false;}).finally(()=>inputBusy=false);};
 api.sendState=state=>{const now=performance.now();if(!active||role!==0||stateBusy||now-lastState<40)return;lastState=now;if(live('state',{state}))return;stateBusy=true;post('state',{state}).catch(()=>{if(stream?.readyState!==1)connected=false;}).finally(()=>stateBusy=false);};
 return api;
}
